version: '3'

tasks:
  run:
    desc: start service
    cmds:
      - go run backend/cmd/api/main.go
    silent: true
  fmt:
    desc: formatting project
    cmds:
      - golangci-lint fmt
    silent: true