version: '3'

tasks:

  build-backend:
    desc: build backend side
    cmds:
      - cd backend && docker build -t self-dev-backend .

  build-frontend:
    desc: build frontend side
    cmds:
      - cd frontend && docker build -t self-dev-frontend .

  run:
    desc: start service
    cmds:
      - docker-compose up -d
    silent: true

  stop:
    desc: stop service
    cmds:
      - docker-compose down
    silent: true

  fmt:
    desc: formatting project
    cmds:
      - golangci-lint fmt
    silent: true      