# -- BUILD STAGE --
FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm npm ci

COPY ./frontend . 

RUN npm run build

# -- RUN STAGE --
FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/dist /app/dist

CMD ["sh"]